# Data Preprocessing

In [ ]:
import pandas as pd
df=pd.read_csv('/content/train.csv', sep=';')

In [ ]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [ ]:
print(df.shape)

(45211, 17)

In [ ]:
print(f"Number of duplicate rows: {df.duplicated().sum()}")

Number of duplicate rows: 0

In [ ]:
df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB

In [ ]:
df['balance']=df['balance'].astype(float)
df['duration']=df['duration'].astype(float)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  float64
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64
 10  month      45211 non-null  object
 11  duration   45211 non-null  float64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: float64(2), int64(5), object(10)
memory usage: 5.9+ MB

In [ ]:
# Option 1: Using the replace method (Quick and clean)
df['pdays'] = df['pdays'].replace(-1, 0)

In [ ]:
y_counts = df['y'].value_counts()
print("Count of 'no' and 'yes' in column 'y':")
display(y_counts)

Count of 'no' and 'yes' in column 'y':

y
no     39922
yes     5289
Name: count, dtype: int64

In [ ]:
# Numerical Columns
Numerical_cols=df.select_dtypes(include=['int64','float64']).columns
Numerical_cols

Index(['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous'], dtype='object')

In [ ]:
# CATEGORICAL COLUMNS ANALYSIS
categorical_cols = df.select_dtypes(include=['object']).columns
categorical_cols

Index(['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact',
       'month', 'poutcome', 'y'],
      dtype='object')

In [ ]:
for col in categorical_cols:
    unique_vals=df[col].unique()
    print(f"\nUnique values in '{col}' ({len(unique_vals)} total):")
    print(unique_vals)

Unique values in 'job' (12 total):
['management' 'technician' 'entrepreneur' 'blue-collar' 'unknown'
 'retired' 'admin.' 'services' 'self-employed' 'unemployed' 'housemaid'
 'student']

Unique values in 'marital' (3 total):
['married' 'single' 'divorced']

Unique values in 'education' (4 total):
['tertiary' 'secondary' 'unknown' 'primary']

Unique values in 'default' (2 total):
['no' 'yes']

Unique values in 'housing' (2 total):
['yes' 'no']

Unique values in 'loan' (2 total):
['no' 'yes']

Unique values in 'contact' (3 total):
['unknown' 'cellular' 'telephone']

Unique values in 'month' (12 total):
['may' 'jun' 'jul' 'aug' 'oct' 'nov' 'dec' 'jan' 'feb' 'mar' 'apr' 'sep']

Unique values in 'poutcome' (4 total):
['unknown' 'failure' 'other' 'success']

Unique values in 'y' (2 total):
['no' 'yes']

In [ ]:
from sklearn.model_selection import train_test_split

# Define features (X) and target (y)
X = df.drop('y', axis=1)
y = df['y']

# Perform stratified splitting
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print("Shapes after stratified splitting:")
print(f"X_train shape: {X_train.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_test shape: {y_test.shape}")

print("\nValue counts of 'y' in original, training, and testing sets:")
print("Original y:")
display(y.value_counts(normalize=True))
print("\ny_train:")
display(y_train.value_counts(normalize=True))
print("\ny_test:")
display(y_test.value_counts(normalize=True))

Shapes after stratified splitting:
X_train shape: (36168, 16)
y_train shape: (36168,)
X_test shape: (9043, 16)
y_test shape: (9043,)

Value counts of 'y' in original, training, and testing sets:
Original y:

y
no     0.883015
yes    0.116985
Name: proportion, dtype: float64

y_train:

y
no     0.883018
yes    0.116982
Name: proportion, dtype: float64

y_test:

y
no     0.883003
yes    0.116997
Name: proportion, dtype: float64

# Model Bulding