# Data Preprocessing

In [2]:
import pandas as pd
df=pd.read_csv('/content/train.csv', sep=';')

In [3]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [4]:
print(df.shape)

(45211, 17)

In [5]:
print(f"Number of duplicate rows: {df.duplicated().sum()}")

Number of duplicate rows: 0

In [6]:
df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB

In [8]:
df['balance']=df['balance'].astype(float)
df['duration']=df['duration'].astype(float)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  float64
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64
 10  month      45211 non-null  object
 11  duration   45211 non-null  float64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: float64(2), int64(5), object(10)
memory usage: 5.9+ MB

In [10]:
# Option 1: Using the replace method (Quick and clean)
df['pdays'] = df['pdays'].replace(-1, 0)

In [11]:
y_counts = df['y'].value_counts()
print("Count of 'no' and 'yes' in column 'y':")
display(y_counts)

Count of 'no' and 'yes' in column 'y':

y
no     39922
yes     5289
Name: count, dtype: int64

In [12]:
# Numerical Columns
Numerical_cols=df.select_dtypes(include=['int64','float64']).columns
Numerical_cols

Index(['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous'], dtype='object')

In [13]:
# CATEGORICAL COLUMNS ANALYSIS
categorical_cols = df.select_dtypes(include=['object']).columns
categorical_cols

Index(['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact',
       'month', 'poutcome', 'y'],
      dtype='object')

In [14]:
for col in categorical_cols:
    unique_vals=df[col].unique()
    print(f"\nUnique values in '{col}' ({len(unique_vals)} total):")
    print(unique_vals)

Unique values in 'job' (12 total):
['management' 'technician' 'entrepreneur' 'blue-collar' 'unknown'
 'retired' 'admin.' 'services' 'self-employed' 'unemployed' 'housemaid'
 'student']

Unique values in 'marital' (3 total):
['married' 'single' 'divorced']

Unique values in 'education' (4 total):
['tertiary' 'secondary' 'unknown' 'primary']

Unique values in 'default' (2 total):
['no' 'yes']

Unique values in 'housing' (2 total):
['yes' 'no']

Unique values in 'loan' (2 total):
['no' 'yes']

Unique values in 'contact' (3 total):
['unknown' 'cellular' 'telephone']

Unique values in 'month' (12 total):
['may' 'jun' 'jul' 'aug' 'oct' 'nov' 'dec' 'jan' 'feb' 'mar' 'apr' 'sep']

Unique values in 'poutcome' (4 total):
['unknown' 'failure' 'other' 'success']

Unique values in 'y' (2 total):
['no' 'yes']

In [15]:
from sklearn.preprocessing import LabelEncoder

# Automatically converts "no" -> 0 and "yes" -> 1
df['y'] = LabelEncoder().fit_transform(df['y'])

In [16]:
from sklearn.model_selection import train_test_split

# Define features (X) and target (y)
X = df.drop('y', axis=1)
y = df['y']

# Perform stratified splitting
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print("Shapes after stratified splitting:")
print(f"X_train shape: {X_train.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_test shape: {y_test.shape}")

print("\nValue counts of 'y' in original, training, and testing sets:")
print("Original y:")
display(y.value_counts(normalize=True))
print("\ny_train:")
display(y_train.value_counts(normalize=True))
print("\ny_test:")
display(y_test.value_counts(normalize=True))

Shapes after stratified splitting:
X_train shape: (36168, 16)
y_train shape: (36168,)
X_test shape: (9043, 16)
y_test shape: (9043,)

Value counts of 'y' in original, training, and testing sets:
Original y:

y
0    0.883015
1    0.116985
Name: proportion, dtype: float64

y_train:

y
0    0.883018
1    0.116982
Name: proportion, dtype: float64

y_test:

y
0    0.883003
1    0.116997
Name: proportion, dtype: float64

## SMOTE TECHNIQUES

In [17]:
pip install imbalanced-learn

Requirement already satisfied: imbalanced-learn in /usr/local/lib/python3.12/dist-packages (0.14.2)
Requirement already satisfied: numpy<3,>=1.25.2 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (2.0.2)
Requirement already satisfied: scipy<2,>=1.11.4 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (1.16.3)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (1.6.1)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.6 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (0.1.6)
Requirement already satisfied: joblib<2,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (3.6.0)

In [18]:
# 1. Identify categorical columns (excluding the target 'y' which is already separated)
categorical_cols = X_train.select_dtypes(include=['object']).columns

# 2. One-hot encode both training and testing feature sets
X_train_encoded = pd.get_dummies(X_train, columns=categorical_cols, drop_first=True)
X_test_encoded = pd.get_dummies(X_test, columns=categorical_cols, drop_first=True)

# 3. Align the columns of both dataframes to ensure they match exactly
X_train_encoded, X_test_encoded = X_train_encoded.align(X_test_encoded, join='left', axis=1, fill_value=0)

print(f"Encoded X_train shape: {X_train_encoded.shape}")
print(f"Encoded X_test shape: {X_test_encoded.shape}")

Encoded X_train shape: (36168, 42)
Encoded X_test shape: (9043, 42)

In [19]:
from imblearn.over_sampling import SMOTE

# 1. Initialize SMOTE with a random state for reproducibility
smote = SMOTE(random_state=42)

# 2. Fit SMOTE and resample ONLY the training data
X_train_resampled, y_train_resampled = smote.fit_resample(X_train_encoded, y_train)

# 3. Verify the new class distribution
print("Original training class distribution:")
print(y_train.value_counts())

print("\nResampled training class distribution (SMOTE):")
print(y_train_resampled.value_counts())

Original training class distribution:
y
0    31937
1     4231
Name: count, dtype: int64

Resampled training class distribution (SMOTE):
y
0    31937
1    31937
Name: count, dtype: int64

**Logistic Regression**

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

# 1. Initialize the base Logistic Regression model
# We increase max_iter to ensure the optimization algorithm converges completely
log_reg = LogisticRegression(max_iter=1000, random_state=42)

# 2. Define the hyperparameter grid to search over
param_grid = {
    'penalty': ['l1', 'l2'],               # Regularization types
    'C': [0.01, 0.1, 1, 10, 100],          # Inverse of regularization strength
    'solver': ['liblinear', 'saga']        # Solvers that support both l1 and l2 penalties
}

# 3. Set up GridSearchCV
# We use scoring='roc_auc' or 'f1' because the original data is highly imbalanced
grid_search = GridSearchCV(
    estimator=log_reg,
    param_grid=param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

# 4. Fit the grid search on the SMOTE resampled training data
print("Starting Hyperparameter Tuning...")
grid_search.fit(X_train_resampled, y_train_resampled)

# 5. Output the best parameters found
print("\nBest Hyperparameters Found:")
print(grid_search.best_params_)

# 6. Extract the best model
best_model = grid_search.best_estimator_

# 7. Evaluate on the ENCODED test data
y_pred = best_model.predict(X_test_encoded)
y_pred_proba = best_model.predict_proba(X_test_encoded)[:, 1]

# 8. Print Evaluation Metrics
print("\n=== Confusion Matrix ===")
print(confusion_matrix(y_test, y_pred))

print("\n=== Classification Report ===")
print(classification_report(y_test, y_pred))

print(f"ROC-AUC Score: {roc_auc_score(y_test, y_pred_proba):.4f}")

Starting Hyperparameter Tuning...
Fitting 5 folds for each of 20 candidates, totalling 100 fits

Best Hyperparameters Found:
{'C': 0.1, 'penalty': 'l2', 'solver': 'liblinear'}

=== Confusion Matrix ===
[[7562  423]
 [ 539  519]]

=== Classification Report ===
              precision    recall  f1-score   support

           0       0.93      0.95      0.94      7985
           1       0.55      0.49      0.52      1058

    accuracy                           0.89      9043
   macro avg       0.74      0.72      0.73      9043
weighted avg       0.89      0.89      0.89      9043

ROC-AUC Score: 0.8488

**Random Forest**

In [25]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

# 1. Initialize the base Random Forest model
rf = RandomForestClassifier(random_state=42)

# 2. Define the hyperparameter grid
rf_param_grid = {
    'n_estimators': [100, 200],          # Number of trees in the forest
    'max_depth': [10, 20, None],         # Maximum depth of the tree
    'min_samples_split': [2, 5],         # Minimum samples required to split a node
    'criterion': ['gini', 'entropy']     # Function to measure the quality of a split
}

# 3. Set up GridSearchCV
rf_grid = GridSearchCV(estimator=rf, param_grid=rf_param_grid, cv=5, scoring='f1', n_jobs=-1, verbose=1)

# 4. Fit on SMOTE training data
print("Tuning Random Forest...")
rf_grid.fit(X_train_resampled, y_train_resampled)
print(f"Best Parameters: {rf_grid.best_params_}")

# 5. Predict and Evaluate
best_rf = rf_grid.best_estimator_
y_pred_rf = best_rf.predict(X_test_encoded)
y_prob_rf = best_rf.predict_proba(X_test_encoded)[:, 1]

print("\n=== Random Forest Classification Report ===")
print(classification_report(y_test, y_pred_rf))
print(f"ROC-AUC Score: {roc_auc_score(y_test, y_prob_rf):.4f}")

Tuning Random Forest...
Fitting 5 folds for each of 24 candidates, totalling 120 fits
Best Parameters: {'criterion': 'gini', 'max_depth': None, 'min_samples_split': 2, 'n_estimators': 200}

=== Random Forest Classification Report ===
              precision    recall  f1-score   support

           0       0.94      0.95      0.94      7985
           1       0.58      0.55      0.57      1058

    accuracy                           0.90      9043
   macro avg       0.76      0.75      0.76      9043
weighted avg       0.90      0.90      0.90      9043

ROC-AUC Score: 0.9229

**XG Boost**

In [ ]:
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, roc_auc_score


# 1. Initialize the base XGBoost model
xgb = XGBClassifier(random_state=42, eval_metric='logloss')

# 2. Define the hyperparameter grid
xgb_param_grid = {
    'n_estimators': [100, 200],
    'learning_rate': [0.01, 0.1, 0.2],   # Step size shrinkage used to prevent overfitting
    'max_depth': [3, 5, 7],              # Maximum depth of a tree
    'subsample': [0.8, 1.0]              # Subsample ratio of the training instances
}

# 3. Set up GridSearchCV
xgb_grid = GridSearchCV(estimator=xgb, param_grid=xgb_param_grid, cv=5, scoring='f1', n_jobs=-1, verbose=1)

# 4. Fit on SMOTE training data
print("Tuning XGBoost...")
xgb_grid.fit(X_train_resampled,y_train_resampled)
print(f"Best Parameters: {xgb_grid.best_params_}")

# 5. Predict and Evaluate
best_xgb = xgb_grid.best_estimator_
y_pred_xgb = best_xgb.predict(X_test_encoded)
y_prob_xgb = best_xgb.predict_proba(X_test_encoded)[:, 1]

print("\n=== XGBoost Classification Report ===")
print(classification_report(y_test, y_pred_xgb))
print(f"ROC-AUC Score: {roc_auc_score(y_test, y_prob_xgb):.4f}")

Tuning XGBoost...
Fitting 5 folds for each of 36 candidates, totalling 180 fits
Best Parameters: {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 100, 'subsample': 1.0}

=== XGBoost Classification Report ===
              precision    recall  f1-score   support

           0       0.95      0.94      0.94      7985
           1       0.56      0.62      0.59      1058

    accuracy                           0.90      9043
   macro avg       0.75      0.78      0.76      9043
weighted avg       0.90      0.90      0.90      9043

ROC-AUC Score: 0.9168

**Catboost**

In [ ]:
!pip install catboost
from catboost import CatBoostClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, roc_auc_score

# 1. Initialize the base CatBoost model (verbose=0 keeps training silent during grid search)
cb = CatBoostClassifier(random_state=42, verbose=0)

# 2. Define the hyperparameter grid
cb_param_grid = {
    'iterations': [100, 200],            # Equivalent to n_estimators
    'learning_rate': [0.03, 0.1],
    'depth': [4, 6, 8],                  # Depth of the tree
    'l2_leaf_reg': [1, 3, 5]             # L2 regularization coefficient
}

# 3. Set up GridSearchCV
cb_grid = GridSearchCV(estimator=cb, param_grid=cb_param_grid, cv=5, scoring='f1', n_jobs=-1, verbose=1)

# 4. Fit on SMOTE training data
print("Tuning CatBoost...")
cb_grid.fit(X_train_resampled, y_train_resampled)
print(f"Best Parameters: {cb_grid.best_params_}")

# 5. Predict and Evaluate
best_cb = cb_grid.best_estimator_
y_pred_cb = best_cb.predict(X_test_encoded)
y_prob_cb = best_cb.predict_proba(X_test_encoded)[:, 1]

print("\n=== CatBoost Classification Report ===")
print(classification_report(y_test, y_pred_cb))
print(f"ROC-AUC Score: {roc_auc_score(y_test, y_prob_cb):.4f}")

Collecting catboost
  Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 4.7 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10
Tuning CatBoost...
Fitting 5 folds for each of 36 candidates, totalling 180 fits
Best Parameters: {'depth': 8, 'iterations': 100, 'l2_leaf_reg': 3, 'learning_rate': 0.03}

=== CatBoost Classification Report ===
              precision    recall  f1-score   support

           0       0.95      0.93      0.94      7985
           1       0.54      0.63      0.58      1058

    accuracy                           0.90      9043
   macro avg       0.75      0.78      0.76      9043
weighted avg       0.90      0.90      0.90      9043

ROC-AUC Score: 0.9162

**Desicion tree**

In [21]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, roc_auc_score

# Set a random state for reproducibility and tune parameters to prevent severe overfitting
dtree = DecisionTreeClassifier(random_state=42)

# Decision Trees don't need scaling, but they highly benefit from depth control
# to prevent memorizing the SMOTE-augmented training data.
dtree_param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [3, 5, 10, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Using n_jobs=-1 to utilize all available CPU cores for the grid search
dtree_grid = GridSearchCV(estimator=dtree, param_grid=dtree_param_grid, cv=5, scoring='f1', n_jobs=-1, verbose=1)

print("Tuning Decision Tree (Optimized Settings)...")
# Ensure X_train_resampled and X_test_encoded have the identical feature columns
dtree_grid.fit(X_train_resampled, y_train_resampled)
print(f"Best Parameters: {dtree_grid.best_params_}")

best_dtree = dtree_grid.best_estimator_
y_pred_dtree = best_dtree.predict(X_test_encoded)
y_prob_dtree = best_dtree.predict_proba(X_test_encoded)[:, 1]

print("\n=== Decision Tree Classification Report ===")
print(classification_report(y_test, y_pred_dtree))
print(f"ROC-AUC Score: {roc_auc_score(y_test, y_prob_dtree):.4f}")

Tuning Decision Tree (Optimized Settings)...
Fitting 5 folds for each of 72 candidates, totalling 360 fits
Best Parameters: {'criterion': 'gini', 'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2}

=== Decision Tree Classification Report ===
              precision    recall  f1-score   support

           0       0.94      0.91      0.92      7985
           1       0.44      0.52      0.48      1058

    accuracy                           0.87      9043
   macro avg       0.69      0.72      0.70      9043
weighted avg       0.88      0.87      0.87      9043

ROC-AUC Score: 0.7170

In [26]:
import pickle
pkl_filename = "random_forest_model.pkl"

print(f"\nSaving the best Random Forest model to disk as '{pkl_filename}'...")
with open(pkl_filename, 'wb') as file:
    pickle.dump(best_rf, file)

print("🚀 Success! The .pkl file has been generated in your working directory.")

Saving the best Random Forest model to disk as 'random_forest_model.pkl'...
🚀 Success! The .pkl file has been generated in your working directory.

In [27]:
from google.colab import files

# Triggers the browser to download the file directly to your local computer
files.download('random_forest_model.pkl')